# Generated by Django 5.0.3 on 2024-04-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('trainID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('horaire', models.CharField(max_length=2000)),
                ('Depart', models.CharField(max_length=1000)),
                ('Arrive', models.CharField(max_length=1000)),
                ('Temps', models.IntegerField()),
            ],
        ),
    ]
